working

diff --git a/dvrpostprocess b/dvrpostprocess
--- a/dvrpostprocess
+++ b/dvrpostprocess
@@ -3,39 +3,29 @@
 source "/opt/galaxymediatools/functions/prechecknl"
 
 LOGF="/video/Incoming/logs/dvrpostporcess.log"
- FNO=${1##*/} # filename only with extentions
- EXT=${1: -3} # extention only
- FPNE="${1%.*}"  # filename with path no extention
- FNPNE="${FPNE##*/}"  # no path no extention
- DIR=$(dirname "${1}") # path only
 
-echo "Staring automatic commercial editor script" >> $LOGF
-
-echo "Full passed filename: $1" >> $LOGF
-echo "Running on file: $FNO" >> $LOGF
-
-echo "Running comskip commercial locator..." >> $LOGF
-/opt/Comskip/comskip "$1" --ini=/opt/Comskip/comskip.ini --output=/video/Other/recordedtv_commercial_cutfiles /video/Other/recordedtv_commercial_cutfiles
+echo " " >> $LOGF
+echo "---------- STARTING RECORDED TV POST PROCESS ----------" >> $LOGF
+echo "Checking transcode server state..." >> $LOGF
+fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
 if [ $? -ne 0 ]; then
-echo "COMSKIP ERROR. Exiting" >> $LOGF
-exit 1
-else
-echo "Comskip processing complete." >> $LOGF
-fi
-
- check here for exit code
- add execute times
-
-echo "Running mencoder to remove commercials..." >> $LOGF
-mencoder "$1" -edl "/video/Other/recordedtv_commercial_cutfiles/$FNPNE.edl" -oac copy -ovc copy -of mpeg -o "TRANSCODE/$FNO"
+   echo "Attempting to wake server $T1NAME..." >> $LOGF
+  wakeonlan $T1MAC 2>/dev/null 1>/dev/null
+  wakeonlan $T1MAC 2>/dev/null 1>/dev/null
+  sleep 15
+  fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
 if [ $? -ne 0 ]; then
-echo "MENCODER ERROR. Exiting" >> $LOGF
-exit 1
-else
-echo "Mencoder processing complete." >> $LOGF
+  echo "$T1NAME failed wake and server is not responding." >> $LOGF
+  exit 1
 fi
+else
 
-mv /TRANSCODE/$FNO $LOGDIR
+ssh $T1INFO /opt/galaxymediatools/dvrprocess/PlexComskip.py "$1" &
 
-echo "Completed automatic commercial editor script" >> $LOGF
+echo "Executing remote PlexComskip script" >> $LOGF
+
+wait
+echo " " >> $LOGF
+echo "---------- COMPLETED RECORDED TV POST PROCESS ----------" >> $LOGF
+fi
 
