working

diff --git a/massmusictrans b/massmusictrans
--- a/massmusictrans
+++ b/massmusictrans
@@ -2,10 +2,11 @@
 
 err_report() {
     echo " "
-    echo "Error on line $1"
+    echo -e "${rred}Error on line $1${nocolor}"
     echo " "
     rm -r /TRANSCODE
     read -r -p "Press any key to exit"
+    exit
 }
 
 LOGF="/video/Incoming/logs/musictranscoder.log"
@@ -35,7 +36,7 @@ if [ "$1" != "-d" ] && [ "$2" != "-d" ] && [ "$3" != "-d" ] && [ "$4" != "-d" ];
 
 . /opt/galaxymediatools/functions/prechecknl
 
-trap 'err_report $LINENO' ERR
+trap 'err_report $LINENO' SIGHUP SIGINT SIGTERM
 
 SOURCEDIR="/music/process/unsorted"
 echo -e "${magenta}Warming Up...${nocolor}"
