working

diff --git a/masstvinteg b/masstvinteg
--- a/masstvinteg
+++ b/masstvinteg
@@ -25,6 +25,10 @@ fi
 touch $LOGF 
 printf "`eval date +%m/%d/%y"-"%H:%M` - *** Script Start \n" >> $LOGF
 echo "Resetting transcode directory $TRANSDIR"
+if [ "$TRANSDIR" == "" ];then
+echo -e "${errorcolor}ERROR! TRANSDIR is null. Exiting."
+exit 1
+fi
 if [ -d $TRANSDIR ]; then
 rm -r $TRANSDIR/* &> /dev/null
 else
diff --git a/masstvtrans b/masstvtrans
--- a/masstvtrans
+++ b/masstvtrans
@@ -40,6 +40,10 @@ printf "`eval date +%m/%d/%y"-"%H:%M` - *** TV Show Transcoder in $TMODE Startin
 touch $LOGF
 echo "Resetting transcode directory $TRANSDIR..."
 printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Resetting Transcode directory on $THISSERVER \n" >> $LOGF
+if [ "$TRANSDIR" == "" ];then
+echo -e "${errorcolor}ERROR! TRANSDIR is null. Exiting."
+exit 1
+fi
 if [ -d $TRANSDIR ]; then
  rm -r $TRANSDIR/* &> /dev/null
 else
diff --git a/transmovie b/transmovie
--- a/transmovie
+++ b/transmovie
@@ -27,6 +27,10 @@ LOGF="$LOGDIR/MVT_$THISSERVER_$CTS.txt"
 echo "Script starting up"
 touch $LOGF 
 printf "`eval date +%m/%d/%y"-"%H:%M` - *** Script Start \n" >> $LOGF
+if [ "$TRANSDIR" == "" ];then
+echo -e "${errorcolor}ERROR! TRANSDIR is null. Exiting."
+exit 1
+fi
 if [ ! -d $TRANSDIR ]; then
  mkdir $TRANSDIR
 fi
