working

diff --git a/remotewake b/remotewake
--- a/remotewake
+++ b/remotewake
@@ -4,43 +4,42 @@ if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
         echo " "
         echo "Galaxy Media Tools - Remote WoL Transcode Server"
         echo " "
+	echo " Usage: <servername> or all for for all servers"
+	echo " "
         echo "-h or --help : Help"
-        echo "-u : Upgrade from git only"
         echo " "
         exit 0
 fi
 
 if [ "$1" == "" ]; then
-	echo "Argument missing. Specify which transcode server to start-up"
+	echo "Argument missing. Specify which transcode server to start-up or all for all"
 	exit 1
 fi
 
 source "/opt/galaxymediatools/functions/prechecknl"
 
-if [ "$1" == "$T1NAME" ]; then
+if [ "$1" == "$T1NAME" ] || [ "$1" == "all" ]; then
  fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
-  if [ "$?" == "0" ]; then
-   echo "$T1NAME server already running."
-   exit 1
+ if [ "$?" == "0" ]; then
+  echo "$T1NAME server already running."
  else
-  echo "Waking transcode server $T1NAME"
-  wakeonlan $T1MAC
+  echo "Waking transcode server $T1NAME..."
+  wakeonlan $T1MAC 2>/dev/null 1>/dev/null
   sleep 3
-  echo -e "Transcode server $T1NAME started"
+  echo -e "Transcode server $T1NAME started."
   exit 0
  fi
-elif [ "$1" == "$T2NAME" ]; then
-fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
+fi
+
+if [ "$1" == "$T2NAME" ] || [ "$1" == "all" ]; then
+ fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
-   echo "$T2NAME server already running."
-   exit 1
+  echo "$T2NAME server already running."
  else
-  echo "Waking transcode server $T2NAME"
-  wakeonlan $T2MAC
+  echo "Waking transcode server $T2NAME..."
+  wakeonlan $T2MAC 2>/dev/null 1>/dev/null
   sleep 3
   echo -e "Transcode server $T2NAME started"
   exit 0
  fi
 fi
-echo "No server exists with that name"
-exit 1
