working

diff --git a/remotesleep b/remotesleep
--- a/remotesleep
+++ b/remotesleep
@@ -2,9 +2,9 @@
 
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
         echo " "
-        echo "Galaxy Media Tools - Remote Sleep Transcode Server"
+        echo "Galaxy Media Tools - Remote Suspend Transcode Server"
         echo " "
-	echo " Usage: <servername> or all for for all servers"
+	echo " Usage: <servername> or all for all servers"
 	echo " "
         echo "-h or --help : Help"
         echo " "
@@ -12,7 +12,7 @@ if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 fi
 
 if [ "$1" == "" ]; then
-	echo "Argument missing. Specify which transcode server to start-up or all for all"
+	echo "Argument missing. Specify which server to suspend or all for all"
 	exit 1
 fi
 
@@ -20,23 +20,30 @@ source "/opt/galaxymediatools/functions/prechecknl"
 
 if [ "$1" == "$T1NAME" ] || [ "$1" == "all" ]; then
  fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
- if [ "$?" == "0" ]; then
-  echo "$T1NAME server is up. Putting to sleep..."
-  ssh $T1INFO "sudo pm-suspend" & 
+  if [ "$?" != "0" ]; then
+  echo "$T1NAME server already suspended."
  else
-  echo "$T1NAME server is already sleeping."
-  exit 1
+  if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
+   echo "NOT Suspending server $T1NAME, because server is busy"
+  else
+   echo "Suspending transcode server $T1NAME"
+   ssh $T1INFO 'sudo pm-suspend' &
+   echo -e "Transcode server $T1NAME suspended"
+  fi
  fi
 fi
 
 if [ "$1" == "$T2NAME" ] || [ "$1" == "all" ]; then
  fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
- if [ "$?" == "0" ]; then
-  echo "$T2NAME server is up. Putting to sleep..."
-  ssh $T2INFO "sudo pm-suspend" &
+  if [ "$?" != "0" ]; then
+   echo "$T2NAME server already suspended."
  else
-  echo "$T2NAME server is already sleeping."
-  exit 1
+  if (ssh $T2INFO '[ -d /var/lock/gtrans.lock ]'); then
+   echo "NOT Suspending server $T2NAME, because server is busy"
+  else
+   echo "Suspending transcode server $T2NAME"
+   ssh $T2INFO 'sudo pm-suspend' &
+   echo -e "Transcode server $T2NAME suspended"
+ fi
  fi
 fi
-
