working

diff --git a/remotetranstv b/remotetranstv
--- a/remotetranstv
+++ b/remotetranstv
@@ -4,6 +4,8 @@ if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
         echo " "
         echo "Galaxy Media Tools - Remote TV Transcoder"
         echo " "
+	echo "Usage: remotetranstv <-g> <server>"
+	echo " "
         echo "-h or --help : Help"
         echo "-g : Span across multiple servers"
         echo " "
@@ -11,47 +13,65 @@ if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 fi
 
 if [ "$1" == "" ]; then
-        echo "Argument missing. Specify which server to transcode on"
+        echo "Argument missing. Specify which server to transcode on or -g"
+        exit 1
+fi
+
+if [ "$2" != "" ]; then
+        echo "Too many arguments. Specify one server to transcode on or -g"
         exit 1
 fi
 
 source /opt/galaxymediatools/precheck
 
-if [ "$1" == "$T1NAME" ]; then
-fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
+checkwake()
+{
+fping -c1 -t300 $2 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
-  echo "Waking transcode server $T1NAME"
-  wakeonlan $T1MAC
+  echo "Waking transcode server $1"
+  wakeonlan $3
   echo "Waiting for startup..."
   sleep 10
-  echo -e "Transcode server $T1NAME started"
- fi
- echo "Starting remote TV Transcode on $T1NAME"
- if [ "$2" == "-r" ]; then
- ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/transtv -gr"
+  echo -e "Transcode server $1 started"
  else
- ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/transtv -g"
+ echo -e "Transcode server $1 is awake"
  fi
- echo -e "Remote auto tv transcode started on $T1NAME"
- exit 0
- elif [ "$1" == "$T2NAME" ]; then
-fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
- if [ "$?" != "0" ]; then 
-  echo "Waking transcode server $T2NAME"
-  wakeonlan $T2MAC
-  echo "Waiting for startup..."
-  sleep 10
-  echo -e "Transcode server $T2NAME started"
- fi
- echo "Starting remote TV Transcode on $T2NAME"
-  if [ "$2" == "-r" ]; then
- ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/transtv -v -r"
- else
- ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/transtv -v"
+}
+
+sendtrans()
+{
+checkwake($1 $2 $3)
+echo "Starting remote TV Transcode on $1"
+if [ "$5" == "g" ]; then
+ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv -g"
+echo -e "Remote auto tv transcode started in span mode on $1"
+elif [ "$5" == "gr" ]; then
+ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv -gr"
+echo -e "Remote auto tv transcode started in span reverse mode on $1"
+elif [ "$5" == "" ]; then
+ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv"
+echo -e "Remote auto tv transcode started in normal mode on $1"
+else
+echo "ERROR in Script. Exiting."
+exit 1
 fi
- echo -e "Remote auto tv transcode started on $T2NAME"
- exit 0
+}
+
+if [ "$1" == "-g" ]; then
+sendtrans($T1NAME $T1IP $T1MAC $T1INFO g)
+sendtrans($T2NAME $T2IP $T2MAC $T2INFO gr)
+echo "Complete."
+exit 0
 fi
+
+if [ "$1" == "$T1NAME" ]; then
+TNAME=$T1NAME; TIP=$T1IP; TMAC=$T1MAC; TINFO=$T1INFO
+elif [ "$1" == "$T1NAME" ];
+TNAME=$T2NAME; TIP=$T2IP; TMAC=$T2MAC; TINFO=$T2INFO
+else
 echo "No server exists with that name"
 exit 1
+fi
 
+sendtrans($TNAME $TIP $TMAC $TINFO)
+echo "Complete."
