working

diff --git a/securityscan b/securityscan
--- a/securityscan
+++ b/securityscan
@@ -6,11 +6,43 @@ LOGF="/video/Incoming/logs/securityscan-$HOSTNAME.log"
 else
 LOGF="/var/log/SECURITYSCAN.log"
 fi
+LOOPCOUNT=0
+WAITHOURS=2
 
 source "/opt/galaxymediatools/functions/prechecknl"
 
+checkplex() {
+PLEXBUSY=`curl -k "https://127.0.0.1:32400/status/sessions?X-Plex-Token=$PLEXTOKEN" | grep 'MediaContainer size="1"' | wc -l`
+if [ $PLEXBUSY -ne 0 ]; then
+ if [ $LOOPCOUNT -eq 0 ]; then
+  log "WARN" "Plex server is busy, postponing securityscan..."
+ fi
+sleep 600
+fi
+((LOOPCOUNT++))
+echo $PLEXBUSY
+}
+
 starttimer
 log "INFO" "---> security scan starting on \"$HOSTNAME\""
+
+if [ "$HOSTNAME" == "$PLEXNAME" ]; then
+starttimer3
+HOURLOOP=$((WAITHOURS * 6))
+until [ $LOOPCOUNT -eq $HOURLOOP ]; do
+PCHECK=$(checkplex)
+if [ $PCHECK -eq 0 ]; then
+LOOPCOUNT=$HOURLOOP
+fi
+done
+ELAPSED3=$((elapsed3))
+NEWST=$(HOURLOOP-1)
+if [ $LOOPCOUNT -gt $NEWST ]; then
+log "ERROR" "Plex still busy after $WAITHOURS Hours. Skipping securityscan. Elapsed: $ELAPSED3"
+exit 1
+fi
+
+fi
 
 log "INFO" "Running system updates..."
 starttimer2
